add-and-remove-functions
mnaibei/To-Do-list-webpack pull request #2
Opened 2023-03-28 19:02 UTC by mnaibei

- Init project using webpack
- Created index and js files dynamically using webpack
- Created todo list
- User can add task
- User can remove task
- Tasks persist in local storage

2023-03-28 19:32 UTC, danmainah requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


# Required Changes ♻️

- [ ] @mnaibei great work on your documentation, however, your live demo link is broken, kindly fix it or remove the section since it's not a requirement for this milestone, also kindly specify your future feature javascript it's not clear.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-28 19:32 UTC, danmainah commented on src/index.js
> +};
- [ ] @mnaibei kindly add a button to delete an individual task currently to remove a task you need to mark it complete then click the `clear all completed` button

2023-03-30 13:33 UTC, franclobo requested changes
Hi @mnaibei, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/228852836-4c757f9b-0b57-4b4d-ab29-e18fc0bf453a.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Good UI ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 13:40 UTC, mnaibei commented on src/modules/tasks.js
> +};
Hi @franclobo thank you for your review., this part is giving me challenge I don't know why it returns undefined., can I work on fixing it later? or can you share some resources to help me fix it

2023-03-30 18:10 UTC, mnaibei commented
**Hello Reviewer this is my final review, please let me know if you require any changes before you submit. 🙏 **

2023-03-30 18:33 UTC, DuaneDave approved these changes
Hi @mnaibei 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ All requested changes have been addressed
✔️ App is working fine

## Before Delete

![before](https://user-images.githubusercontent.com/84930355/228931161-2577844b-3aaa-4248-b26e-3995f1b2b468.PNG)

## After Delete

![after](https://user-images.githubusercontent.com/84930355/228931366-9c1b17ec-6259-4d23-8e8d-849a72244e6e.PNG)



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 18:36 UTC, merged